"""
reporting/comparison.py
-----------------------
Writes comparison.csv, comparison.json, and the auto-generated model.py script.
No PDF dependencies — pure stdlib + pathlib.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


def write_comparison(records: list[dict], output_dir: Path) -> None:
    """Write comparison.csv and comparison.json from decision log records."""
    rows = []
    for rec in records:
        m   = rec["state_snapshot"]["metrics"]
        sec = m.get("secondary", {})
        sig = rec["state_snapshot"]["signals"]
        active = [k for k, v in sig.items() if not k.endswith("_confidence") and v != "none"]
        rows.append({
            "iteration":      rec.get("iteration"),
            "model":          rec["state_snapshot"]["model"]["model_name"],
            "action":         rec["selected_action"]["action_type"],
            "trigger":        rec["selected_action"]["reason"]["trigger"],
            "confidence":     rec["selected_action"].get("confidence"),
            "primary_metric": m.get("primary"),
            "train_val_gap":  m.get("train_val_gap"),
            "accuracy":       sec.get("accuracy"),
            "f1_score":       sec.get("f1_score"),
            "precision":      sec.get("precision"),
            "recall":         sec.get("recall"),
            "mse":            sec.get("mse"),
            "r2":             sec.get("r2"),
            "slope":          rec["state_snapshot"]["trajectory"]["slope"],
            "volatility":     rec["state_snapshot"]["trajectory"]["volatility"],
            "runtime":        rec["state_snapshot"]["resources"]["runtime"],
            "active_signals": ", ".join(active),
        })

    if not rows:
        return

    csv_path = output_dir / "comparison.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    (output_dir / "comparison.json").write_text(json.dumps(rows, indent=2), encoding="utf-8")

    budget_artifact = output_dir / "artifacts" / "budget_accounting.json"
    if budget_artifact.exists():
        (output_dir / "budget_accounting.json").write_text(budget_artifact.read_text(encoding="utf-8"), encoding="utf-8")


def generate_model_script(run_id: str, output_dir: Path, records: list[dict]) -> Path:
    """Generate a standalone model.py that loads and uses the best model."""
    best_metric, best_name, best_params = -1.0, "UnknownModel", {}
    for rec in records:
        primary = rec["state_snapshot"]["metrics"].get("primary") or 0.0
        if primary > best_metric:
            best_metric = primary
            best_name   = rec["state_snapshot"]["model"]["model_name"]
            best_params = rec["state_snapshot"]["model"].get("hyperparameters", {})

    model_pkl = output_dir / "artifacts" / "model.pkl"
    script = f'''"""
model.py — Auto-generated by StratML
Run ID : {run_id}
Model  : {best_name}
Metric : {best_metric:.4f}
"""
import joblib, numpy as np
from pathlib import Path

model = joblib.load(Path(r"{model_pkl}"))
hyperparameters = {best_params!r}

def predict(X):
    return model.predict(np.array(X))

def predict_proba(X):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(np.array(X))
    raise NotImplementedError(f"{{type(model).__name__}} does not support predict_proba")

if __name__ == "__main__":
    print(f"Model : {{type(model).__name__}}")
    print(f"Params: {{model.get_params()}}")
'''
    script_path = output_dir / "artifacts" / "model.py"
    script_path.write_text(script, encoding="utf-8")
    return script_path
