"""
schemas.py
----------
Core contracts shared between the Execution team (Team A) and the Decision
team (Team B).

These objects define the boundary interface.  Once frozen, neither team
modifies these schemas without a joint agreement.

Objects defined here:
    ExperimentResult   — Team A → Team B, produced after every training run
    StateObject        — Team B internal, built from ExperimentResult
    CandidateAction    — Team B internal, generated by action_generator
    ActionDecision     — Team B → Team A, one per iteration
    DecisionRecord     — Team B internal, persisted to decision log
    AgentScore         — Team B internal, one per deliberation agent

Cross-team boundary rule
------------------------
    ExperimentResult  ←  Team A produces
    ActionDecision    ←  Team B produces
    StateObject       ←  Team B internal (never sent to Team A)
"""

from __future__ import annotations

from typing import Annotated, Optional, Union
from pydantic import BaseModel, BeforeValidator, Field


# ---------------------------------------------------------------------------
# Embedded sub-objects reused across schemas
# ---------------------------------------------------------------------------

class PreprocessingConfig(BaseModel):
    """Preprocessing decisions — embedded in both ActionDecision and ExperimentResult."""

    missing_value_strategy: str = Field(..., pattern="^(mean|median|mode|drop)$")
    scaling: str = Field(..., pattern="^(standard|minmax|robust|none)$")
    encoding: str = Field(..., pattern="^(onehot|label|none)$")
    imbalance_strategy: str = Field(..., pattern="^(oversample|undersample|none)$")
    feature_selection: str = Field(..., pattern="^(variance_threshold|none)$")


class ExperimentMetrics(BaseModel):
    """All numeric outputs from a single training run."""

    accuracy: Optional[float] = None
    f1_score: Optional[float] = None
    precision: Optional[float] = None
    recall: Optional[float] = None
    train_loss: Optional[float] = None
    validation_loss: Optional[float] = None
    mse: Optional[float] = None
    rmse: Optional[float] = None
    r2: Optional[float] = None


class ResourceUsage(BaseModel):
    gpu_used: bool = False
    gpu_memory_gb: float = 0.0
    cpu_time_sec: float = 0.0


class ArtifactRefs(BaseModel):
    model_path: str
    metrics_file: str
    tensorboard_logs: str


# ---------------------------------------------------------------------------
# Cross-team: ExperimentResult  (Team A → Team B)
# ---------------------------------------------------------------------------

class ExperimentResult(BaseModel):
    """
    Produced by Team A after every training run.
    Consumed by Team B's state_builder to construct a StateObject.
    """

    # --- identification ---
    experiment_id: str
    iteration: int
    dataset_name: str

    # --- model ---
    model_name: str
    model_type: str = Field(..., pattern="^(ml|dl)$")
    hyperparameters: dict

    # --- preprocessing actually applied ---
    preprocessing_applied: PreprocessingConfig

    # --- outputs ---
    metrics: ExperimentMetrics
    train_curve: list[float]
    validation_curve: list[float]

    # --- system ---
    runtime: float
    resource_usage: ResourceUsage
    artifacts: ArtifactRefs

    # --- training metadata (DL-populated, None for ML) ---
    early_stopped: Optional[bool] = None   # True if early stopping triggered
    best_epoch: Optional[int] = None       # epoch index with lowest val loss
    status: Optional[str] = None           # e.g. "completed" or "failed"
    failed: Optional[bool] = None          # True if run explicitly failed


# ---------------------------------------------------------------------------
# Cross-team: ActionDecision  (Team B → Team A)
# ---------------------------------------------------------------------------

class BootstrapContext(BaseModel):
    """Present only on iteration 0 — records that the decision came from DataProfile."""

    source: str = "dataprofile"
    strategy: str  # e.g. "tree_baseline", "linear_baseline"


class DecisionReason(BaseModel):
    trigger: str
    evidence: dict = Field(default_factory=dict)
    source: str = Field(default="rule", pattern="^(bootstrap|rule|llm|value_model|hybrid|fallback|learned)$")


def _coerce_reason(v):
    if isinstance(v, str):
        return {"trigger": v, "evidence": {}, "source": "rule"}
    return v


ReasonField = Annotated[DecisionReason, BeforeValidator(_coerce_reason)]


class AgentScore(BaseModel):
    performance: Optional[float] = None
    efficiency: Optional[float] = None
    stability: Optional[float] = None


class ActionDecision(BaseModel):
    """
    Produced by Team B after every StateObject evaluation.
    Consumed by Team A to configure and run the next experiment.
    """

    # --- identification ---
    experiment_id: str
    iteration: int = 0

    # --- action ---
    action_type: str
    parameters: dict

    # --- preprocessing plan for next run ---
    preprocessing: PreprocessingConfig

    # --- bootstrap (iteration 0 only) ---
    bootstrap_context: Optional[BootstrapContext] = None

    # --- decision intelligence ---
    expected_gain: Optional[float] = None
    expected_cost: float = 0.0
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)

    # --- multi-agent scores ---
    agent_scores: AgentScore = Field(default_factory=AgentScore)

    # --- structured reason ---
    reason: ReasonField


# ---------------------------------------------------------------------------
# Team B internal: CandidateAction
# ---------------------------------------------------------------------------

class CandidateAction(BaseModel):
    """
    A possible next action generated by action_generator.py.
    Evaluated by the policy selector before one is chosen.
    """

    action_type: str
    parameters: dict


# ---------------------------------------------------------------------------
# Team B internal: StateObject
# ---------------------------------------------------------------------------

class SecondaryMetrics(BaseModel):
    accuracy: Optional[float] = None
    precision: Optional[float] = None
    recall: Optional[float] = None
    f1_score: Optional[float] = None
    mse: Optional[float] = None
    rmse: Optional[float] = None
    r2: Optional[float] = None


class StateMetrics(BaseModel):
    primary: float
    secondary: SecondaryMetrics
    train_val_gap: float


class StateTrajectory(BaseModel):
    history_length: int
    improvement_rate: float
    slope: float
    volatility: float
    best_score: float
    mean_score: float
    steps_since_improvement: int
    trend: str = Field(..., pattern="^(improving|stagnating|degrading)$")


class StateDataset(BaseModel):
    num_samples: int
    num_features: int
    feature_to_sample_ratio: float
    missing_ratio: float
    class_distribution: Optional[dict] = None
    imbalance_ratio: Optional[float] = None
    dataset_fingerprint: Optional[str] = None


class StateModel(BaseModel):
    model_name: str
    model_type: str
    hyperparameters: dict
    complexity_hint: Optional[str] = Field(default=None, pattern="^(low|medium|high)$")
    runtime: float
    convergence_epoch: int
    early_stopped: Optional[bool] = None


class StateGeneralization(BaseModel):
    train_loss: float
    validation_loss: float
    gap: float


class StateResources(BaseModel):
    runtime: float
    gpu_used: bool
    cpu_time: float
    remaining_budget: Optional[float] = None
    budget_exhausted: bool = False


class StateSearch(BaseModel):
    models_tried: list[str]
    unique_models_count: int
    repeated_configs: int


SignalStrength = str  # "none" | "weak" | "strong"


class StateSignals(BaseModel):
    # fitting
    underfitting: SignalStrength = "none"
    underfitting_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    overfitting: SignalStrength = "none"
    overfitting_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    well_fitted: SignalStrength = "none"
    well_fitted_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # convergence
    converged: SignalStrength = "none"
    converged_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    stagnating: SignalStrength = "none"
    stagnating_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    diverging: SignalStrength = "none"
    diverging_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # stability
    unstable_training: SignalStrength = "none"
    unstable_training_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    high_variance: SignalStrength = "none"
    high_variance_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # efficiency
    too_slow: SignalStrength = "none"
    too_slow_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # optimization
    plateau_detected: SignalStrength = "none"
    plateau_detected_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    diminishing_returns: SignalStrength = "none"
    diminishing_returns_confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class StateUncertainty(BaseModel):
    prediction_variance: Optional[float] = None
    confidence: Optional[float] = None


class StateActionContext(BaseModel):
    previous_action: Optional[str] = None
    previous_action_success: Optional[bool] = None
    action_effect_magnitude: Optional[float] = None
    previous_signals: Optional["StateSignals"] = None


class StateConstraints(BaseModel):
    allowed_models: list[str]
    max_iterations: int
    time_budget: Optional[float] = None


class StateMeta(BaseModel):
    experiment_id: str
    iteration: int
    timestamp: str


class StateObjective(BaseModel):
    primary_metric: str
    optimization_goal: str = Field(..., pattern="^(maximize|minimize)$")


class StateObject(BaseModel):
    """
    The central state representation built by Team B's state_builder.
    This is the CONTRACT between Dev B (state pipeline) and Dev A (decision engine).

    DO NOT MODIFY AFTER FREEZE.
    """

    meta: StateMeta
    objective: StateObjective
    metrics: StateMetrics
    trajectory: StateTrajectory
    dataset: StateDataset
    model: StateModel
    generalization: StateGeneralization
    resources: StateResources
    search: StateSearch
    signals: StateSignals
    uncertainty: StateUncertainty = Field(default_factory=StateUncertainty)
    action_context: StateActionContext = Field(default_factory=StateActionContext)
    constraints: StateConstraints


# ---------------------------------------------------------------------------
# Team B internal: DecisionRecord  (persisted to decision log)
# ---------------------------------------------------------------------------

class DecisionRecord(BaseModel):
    """Full record of one decision cycle — written to logs/decision_logs.json."""

    experiment_id: str
    iteration: int
    timestamp: str
    state_snapshot: StateObject
    candidate_actions: list[CandidateAction]
    selected_action: ActionDecision
    coordinator_weights: Optional[dict[str, float]] = None
    ranked_candidates: Optional[list[dict]] = None
    execution_result: Optional[dict] = None
    evaluator_result: Optional[dict] = None
    next_state_id: Optional[str] = None
